name: Compatibility

on:
  push:
    branches: [main]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-node.yml@086f2d88815451da2cba7dc9e6e044d86c66743c # v8.2.0
    with:
      node-versions: '["20","22","24"]'
